# Generated by Django 5.2.10 on 2026-03-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='agegrouptag',
            name='value',
            field=models.CharField(choices=[('2-3', '2-3 года'), ('4-5', '4-5 лет'), ('6-7', '6-7 лет')], max_length=10, unique=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='developmentareatag',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.agegrouptag', verbose_name='Возрастные группы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='development_areas',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.developmentareatag', verbose_name='Области развития'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtypes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.subtype', verbose_name='Подтипы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.theme', verbose_name='Темы'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
