# Generated by Django 5.2.10 on 2026-04-20 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_catalog_search_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обработан в'),
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пользователь уведомлён об отклонении в'),
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения (для пользователя)'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На модерации'), ('PUBLISHED', 'Опубликован'), ('REJECTED', 'Отклонён')], db_index=True, default='PENDING', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='review_unique_per_product_user'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
    ]
