# Generated by Django 5.2.10 on 2026-04-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promocodes", "0001_initial"),
        ("products", "0005_review_moderation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reward_email_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Письмо с промокодом отправлено в"),
        ),
        migrations.AddField(
            model_name="review",
            name="reward_issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Промокод выдан в"),
        ),
        migrations.AddField(
            model_name="review",
            name="reward_promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewarded_reviews",
                to="promocodes.promocode",
                verbose_name="Выданный промокод за отзыв",
            ),
        ),
    ]
