# Generated by Django 5.2.10 on 2026-07-05 20:54

import apps.products.models
import apps.products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_reward_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=apps.products.storage.get_product_image_storage, upload_to=apps.products.models.product_image_upload_to),
        ),
    ]
