# Generated by Django 5.2.10 on 2026-07-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtype',
            name='category',
        ),
    ]
