# Generated by Django 5.2.10 on 2026-08-21 18:58

from django.db import migrations, models


def set_existing_products_published(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.update(is_published=True)


def unset_existing_products_published(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_subtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликован'),
        ),
        migrations.RunPython(set_existing_products_published, unset_existing_products_published),
    ]
