# Generated by Django 5.2.10 on 2026-08-07 20:57

import apps.products.models
import apps.products.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_subtype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделить')),
                ('label', models.CharField(blank=True, max_length=64, verbose_name='Метка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар в подборке',
                'verbose_name_plural': 'Товары в подборке',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('cover_image', models.ImageField(blank=True, storage=apps.products.storage.get_product_image_storage, upload_to=apps.products.models.collection_cover_upload_to, verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('robots', models.CharField(choices=[('index,follow', 'index,follow'), ('noindex,follow', 'noindex,follow')], default='index,follow', max_length=32, verbose_name='Robots')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('show_in_catalog', models.BooleanField(default=False, verbose_name='Показывать в каталоге')),
                ('show_in_navigation', models.BooleanField(default=False, verbose_name='Показывать в навигации')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Показывать в футере')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('badge', models.CharField(blank=True, max_length=32, verbose_name='Бейдж')),
                ('campaign_code', models.SlugField(blank=True, max_length=64, verbose_name='Код кампании (UTM)')),
                ('publish_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Публикация с')),
                ('publish_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Публикация до')),
                ('min_products_to_publish', models.PositiveSmallIntegerField(default=5, verbose_name='Минимум товаров для публикации')),
                ('products', models.ManyToManyField(related_name='collections', through='products.CollectionProduct', to='products.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Тематическая подборка',
                'verbose_name_plural': 'Тематические подборки',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='collectionproduct',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='products.productcollection', verbose_name='Подборка'),
        ),
        migrations.AddConstraint(
            model_name='collectionproduct',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='collection_product_unique'),
        ),
    ]
