# Generated by Django 5.2.10 on 2026-03-22 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_currency_alter_agegrouptag_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('PENDING', 'В обработке'), ('WAITING_FOR_PAYMENT', 'Ожидает оплату'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('FAILED', 'Ошибка')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('checkout_type', models.CharField(choices=[('AUTHENTICATED', 'Авторизованный'), ('GUEST', 'Гостевой')], max_length=16, verbose_name='Тип оформления')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма позиций')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('items_count', models.PositiveSmallIntegerField(verbose_name='Количество позиций')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён в')),
                ('failure_reason', models.CharField(blank=True, max_length=128, null=True, verbose_name='Причина ошибки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('EXPRESS_PAY', 'Express Pay')], default='EXPRESS_PAY', max_length=32, verbose_name='Провайдер')),
                ('provider_invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса у провайдера')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплату'), ('EXPIRED', 'Истёк'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('REFUNDED', 'Возвращён')], default='PENDING', max_length=16, verbose_name='Статус инвойса')),
                ('invoice_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён в')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает в')),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка статуса')),
                ('raw_create_response', models.JSONField(blank=True, null=True, verbose_name='Ответ создания инвойса')),
                ('raw_last_status_response', models.JSONField(blank=True, null=True, verbose_name='Последний ответ статуса')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('category_snapshot', models.CharField(max_length=100, verbose_name='Категория товара')),
                ('unit_price_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('line_total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма позиции')),
                ('product_slug_snapshot', models.SlugField(blank=True, null=True, verbose_name='Слаг товара')),
                ('product_image_snapshot', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('EXPRESS_PAY', 'Express Pay')], default='EXPRESS_PAY', max_length=32, verbose_name='Провайдер')),
                ('provider_event_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ события провайдера')),
                ('cmd_type', models.PositiveSmallIntegerField(verbose_name='Тип команды')),
                ('provider_payment_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа у провайдера')),
                ('provider_invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса у провайдера')),
                ('provider_status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код статуса провайдера')),
                ('invoice_status', models.CharField(blank=True, choices=[('PENDING', 'Ожидает оплату'), ('EXPIRED', 'Истёк'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('REFUNDED', 'Возвращён')], max_length=16, null=True, verbose_name='Нормализованный статус')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name='Ошибка обработки')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.invoice', verbose_name='Инвойс')),
            ],
            options={
                'verbose_name': 'Событие оплаты',
                'verbose_name_plural': 'События оплаты',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
