# Generated by Django 5.2.10 on 2026-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_account_no",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=22,
                null=True,
                unique=True,
                verbose_name="Номер лицевого счёта для оплаты",
            ),
        ),
    ]
