# Generated by Django 5.2.10 on 2026-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('PG', 'Сайт PaliGames'), ('TG', 'Telegram'), ('IG', 'Instagram')], default='PG', max_length=2, verbose_name='Источник заказа'),
        ),
    ]
