# Generated by Django 5.2.10 on 2026-03-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentevent',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentEvent',
        ),
    ]
