# Generated by Django 5.2.10 on 2026-04-18 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_paymentevent_invoice_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка, %'),
        ),
    ]
