# Generated by Django 5.2.10 on 2026-04-18 09:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_amount_and_more'),
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promocodes.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_snapshot',
            field=models.CharField(blank=True, max_length=32, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_eligible_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма подходящих под промокод товаров'),
        ),
    ]
