# Generated by Django 5.2.10 on 2026-04-18 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_promo_code_order_promo_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discounted_line_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма позиции со скидкой'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promo_eligible',
            field=models.BooleanField(default=False, verbose_name='Применён промокод'),
        ),
    ]
