# Generated by Django 5.2.10 on 2026-04-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_idempotency_key",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Ключ идемпотентности оформления",
            ),
        ),
    ]
