# Generated by Django 5.2.10 on 2026-04-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_checkout_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_FOR_PAYMENT', 'Ожидает оплату'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('FAILED', 'Ошибка')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
