# Generated by Django 5.2.10 on 2026-04-19 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_status_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество позиций'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма позиций'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итоговая сумма'),
        ),
    ]
