# Generated by Django 5.2.10 on 2026-04-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promocodes", "0002_promocode_is_reward"),
        ("orders", "0010_order_amount_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reward_email_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Письмо с промокодом за заказ отправлено в"),
        ),
        migrations.AddField(
            model_name="order",
            name="reward_issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Промокод за заказ выдан в"),
        ),
        migrations.AddField(
            model_name="order",
            name="reward_promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewarded_orders",
                to="promocodes.promocode",
                verbose_name="Выданный промокод за заказ",
            ),
        ),
    ]
