# Generated by Django 5.2.10 on 2026-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_reward_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='analytics_storage_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на аналитику (GA4) при оформлении'),
        ),
    ]
