# Generated by Django 5.2.10 on 2026-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_yandex_metrica_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возвращён в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING_FOR_PAYMENT', 'Ожидает оплату'), ('PAID', 'Оплачен'), ('REFUNDED', 'Возврат'), ('CANCELED', 'Отменён'), ('FAILED', 'Ошибка')], default='CREATED', max_length=20, verbose_name='Статус'),
        ),
    ]
