# Generated by Django 5.2.10 on 2026-09-22 20:33

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_refunded_at_alter_order_status'),
        ('promocodes', '0002_promocode_is_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(django.db.models.functions.text.Lower('email'), condition=models.Q(('user__isnull', True)), name='orders_guest_email_lower_idx'),
        ),
    ]
