# Generated by Django 5.2.10 on 2026-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_orders_guest_email_lower_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ga4_client_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='GA4 client_id (browser)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ga4_purchase_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GA4 purchase отправлен в'),
        ),
        migrations.AddField(
            model_name='order',
            name='ga4_session_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='GA4 session_id (browser)'),
        ),
    ]
