# Generated by Django 5.2.10 on 2026-04-19 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор')),
                ('payment_account_no', models.CharField(blank=True, editable=False, max_length=22, null=True, unique=True, verbose_name='Номер лицевого счёта для оплаты')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('READY', 'Готова'), ('WAITING_FOR_PAYMENT', 'Ожидает оплаты'), ('PAYMENT_EXPIRED', 'Срок оплаты истёк'), ('DELIVERED', 'Передана'), ('CANCELLED', 'Отменена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('PG', 'Сайт PaliGames'), ('TG', 'Telegram'), ('IG', 'Instagram')], default='PG', max_length=2, verbose_name='Источник заявки')),
                ('contact_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон')),
                ('idea', models.TextField(verbose_name='Идея игры')),
                ('audience', models.TextField(verbose_name='Аудитория')),
                ('timing', models.TextField(verbose_name='Срок изготовления')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('deadline_reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_game_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра на заказ',
                'verbose_name_plural': 'Игры на заказ',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomGameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file_key', models.CharField(max_length=512, unique=True, verbose_name='Ключ файла')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='custom_games.customgamerequest', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomGameDownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('token_hash', models.CharField(max_length=128, unique=True, verbose_name='Хеш токена')),
                ('token_prefix', models.CharField(db_index=True, max_length=16, verbose_name='Префикс токена')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('max_downloads', models.PositiveIntegerField(default=3, verbose_name='Максимальное количество загрузок')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Количество загрузок')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='custom_games.customgamerequest', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Токен загрузки',
                'verbose_name_plural': 'Токены загрузки',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
