# Generated by Django 5.2.10 on 2026-09-10 20:17

import apps.managed_links.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('token', models.CharField(default=apps.managed_links.tokens.generate_managed_link_token, editable=False, max_length=32, unique=True, verbose_name='Токен')),
                ('token_prefix', models.CharField(db_index=True, editable=False, max_length=16, verbose_name='Префикс токена')),
                ('s3_file_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Ключ S3')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('external_url', models.URLField(blank=True, max_length=2048, verbose_name='Внешняя ссылка')),
                ('qr_logo', models.ImageField(blank=True, null=True, upload_to='managed_links/qr_logos/', verbose_name='Логотип QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Управляемая ссылка',
                'verbose_name_plural': 'Управляемые ссылки',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('s3_file_key', ''), _negated=True), models.Q(('external_url', ''), _negated=True), _connector='OR'), name='managed_link_active_requires_destination')],
            },
        ),
    ]
