# Generated by Django 5.2.10 on 2026-09-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managed_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedlink',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
