# Generated by Django 5.2.10 on 2026-03-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_remove_paymentevent_invoice_delete_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('EXPRESS_PAY', 'Express Pay')], default='EXPRESS_PAY', max_length=32, verbose_name='Провайдер')),
                ('provider_invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса у провайдера')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплату'), ('EXPIRED', 'Истёк'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('REFUNDED', 'Возвращён')], default='PENDING', max_length=16, verbose_name='Статус инвойса')),
                ('invoice_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён в')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает в')),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка статуса')),
                ('raw_create_response', models.JSONField(blank=True, null=True, verbose_name='Ответ создания инвойса')),
                ('raw_last_status_response', models.JSONField(blank=True, null=True, verbose_name='Последний ответ статуса')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'db_table': 'orders_invoice',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('EXPRESS_PAY', 'Express Pay')], default='EXPRESS_PAY', max_length=32, verbose_name='Провайдер')),
                ('provider_event_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ события провайдера')),
                ('cmd_type', models.PositiveSmallIntegerField(verbose_name='Тип команды')),
                ('provider_payment_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа у провайдера')),
                ('provider_invoice_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса у провайдера')),
                ('provider_status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код статуса провайдера')),
                ('invoice_status', models.CharField(blank=True, choices=[('PENDING', 'Ожидает оплату'), ('EXPIRED', 'Истёк'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменён'), ('REFUNDED', 'Возвращён')], max_length=16, null=True, verbose_name='Нормализованный статус')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('currency', models.PositiveSmallIntegerField(choices=[(933, 'BYN'), (840, 'USD'), (978, 'EUR'), (643, 'RUB')], default=933, verbose_name='Валюта')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('processing_error', models.TextField(blank=True, null=True, verbose_name='Ошибка обработки')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.invoice', verbose_name='Инвойс')),
            ],
            options={
                'verbose_name': 'Событие оплаты',
                'verbose_name_plural': 'События оплаты',
                'db_table': 'orders_paymentevent',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
