# Generated by Codex on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("custom_games", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="custom_game_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="custom_games.customgamerequest",
                verbose_name="Игра на заказ",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=(
                    Q(("custom_game_request__isnull", True), ("order__isnull", False))
                    | Q(("custom_game_request__isnull", False), ("order__isnull", True))
                ),
                name="payments_invoice_exactly_one_target",
            ),
        ),
    ]
