# Generated by Django 5.2.10 on 2026-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_custom_game_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_email_sent_for_provider_invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса провайдера, для которого отправлено письмо об оплате'),
        ),
    ]
