# Generated by Django 5.2.10 on 2026-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_payment_email_sent_for_provider_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_reminder_sent_for_provider_invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер инвойса провайдера, для которого отправлено напоминание об оплате'),
        ),
    ]
