# Generated by Django 5.2.10 on 2026-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_games', '0002_refactor_custom_game_request_fields'),
        ('orders', '0014_order_refunded_at_alter_order_status'),
        ('payments', '0004_invoice_payment_reminder_sent_for_provider_invoice_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payments_invoice_paid_requires_paid_at'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_invoice_no__isnull', False), models.Q(('provider_invoice_no', ''), _negated=True)), fields=('provider', 'provider_invoice_no'), name='payments_invoice_unique_provider_invoice_no'),
        ),
    ]
