# Generated by Django 5.2.10 on 2026-04-24 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_analytics_storage_consent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataProcessingConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('policy_version', models.PositiveSmallIntegerField(verbose_name='Версия политики')),
                ('granted', models.BooleanField(verbose_name='Согласие')),
                ('source', models.CharField(choices=[('REGISTRATION_PASSWORD', 'Регистрация (пароль)'), ('OAUTH_FIRST_LOGIN', 'Первый вход (OAuth)'), ('GUEST_CHECKOUT', 'Гостевой заказ'), ('POLICY_RECONFIRM', 'Повтор при смене политики')], max_length=32, verbose_name='Источник')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=256, verbose_name='Агент пользователя')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pd_consent_log_entries', to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pd_consent_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='users_perso_email_44f739_idx')],
            },
        ),
    ]
