# Generated by Django 5.2.10 on 2026-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personaldataprocessingconsentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personaldataprocessingconsentlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Лог согласия на обработку персональных данных",
                "verbose_name_plural": "Логи согласий на обработку персональных данных",
            },
        ),
    ]
