# Generated by Django 5.2.10 on 2026-04-18 09:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_discount_amount_and_more'),
        ('products', '0004_catalog_search_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма подходящих товаров')),
                ('max_total_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общий лимит использований')),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит на пользователя')),
                ('max_redemptions_per_email', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит на email')),
                ('assigned_email', models.EmailField(blank=True, max_length=254, verbose_name='Назначен email')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Назначен пользователю')),
                ('categories', models.ManyToManyField(blank=True, related_name='promo_codes', to='products.category', verbose_name='Категории')),
                ('products', models.ManyToManyField(blank=True, related_name='promo_codes', to='products.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма товаров')),
                ('eligible_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма подходящих товаров')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemption', to='orders.order', verbose_name='Заказ')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promocodes.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='promocode_code_upper_unique'),
        ),
    ]
