# Generated by Django 5.2.10 on 2026-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promocodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_reward",
            field=models.BooleanField(default=False, verbose_name="Промокод-награда"),
        ),
    ]
