# Generated by Django 5.2.10 on 2026-07-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0003_alter_notificationoutbox_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipient', models.EmailField(db_index=True, max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=998, verbose_name='Тема')),
                ('template_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ шаблона')),
                ('notification_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('QUEUED', 'В очереди'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка'), ('SUPPRESSED', 'Подавлено')], db_index=True, default='QUEUED', max_length=16, verbose_name='Статус')),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SES_SMTP', 'Amazon SES SMTP'), ('SES_API', 'Amazon SES API')], default='SMTP', max_length=16, verbose_name='Провайдер')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message-ID')),
                ('smtp_response', models.TextField(blank=True, null=True, verbose_name='Ответ SMTP')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Метаданные')),
                ('notification_outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notificationoutbox', verbose_name='Outbox-уведомление')),
            ],
            options={
                'verbose_name': 'Лог email',
                'verbose_name_plural': 'Логи email',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emails_emai_status_0b5614_idx'), models.Index(fields=['notification_type', 'status'], name='emails_emai_notific_c3a295_idx')],
            },
        ),
    ]
