# Generated by Django 5.2.10 on 2026-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('reason', models.CharField(choices=[('HARD_BOUNCE', 'Hard bounce'), ('COMPLAINT', 'Complaint'), ('MANUAL', 'Manual'), ('UNSUBSCRIBE', 'Unsubscribe')], max_length=16, verbose_name='Причина')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='Источник')),
                ('suppressed_at', models.DateTimeField(auto_now_add=True, verbose_name='Подавлено в')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Подавление email',
                'verbose_name_plural': 'Подавления email',
                'ordering': ['-suppressed_at', '-id'],
                'indexes': [models.Index(fields=['active', 'email'], name='emails_emai_active_9ea200_idx')],
            },
        ),
    ]
