# Generated by Django 5.2.10 on 2026-04-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationoutbox',
            new_name='notificatio_notific_5f0d13_idx',
            old_name='notificatio_notific_605d9f_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationoutbox',
            new_name='notificatio_content_06ddea_idx',
            old_name='notificatio_content_5fd785_idx',
        ),
    ]
