# Generated by Django 5.2.10 on 2026-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notificatio_notific_605d9f_idx_notificatio_notific_5f0d13_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoutbox',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram')], default='EMAIL', max_length=16, verbose_name='Канал'),
        ),
    ]
