# Generated by Django 5.2.10 on 2026-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_alter_notificationoutbox_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('object_id__isnull', False), ('status__in', ['PENDING', 'PROCESSING', 'DELIVERING'])), fields=('notification_type', 'content_type', 'object_id', 'channel'), name='notifications_outbox_one_inflight_per_target'),
        ),
    ]
